# Generated by Django 5.2.4 on 2025-08-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
