# Generated by Django 5.2.4 on 2025-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0003_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
